[package]
name = "rust-sqlite-seaorm"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "0.10", features = ["sqlx-sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"



